### ISSUE TITLE
feature request: remove metadata from clipboard contents

### ISSUE THREAD

**Issue by nmz787-intel** [tdalon/ahk#11]
Hi, copying from Teams often includes unselected metadata (username and timestamp) and I would like to remove this.
I see AHK can modify clipboard contents (https://www.autohotkey.com/board/topic/61302-modify-clipboard-contents/)  so I'm wondering if you have had any experience trying to use this to get Teams clipboard copy to behave as "old" computer users expect (i.e. copy only what is selected).
I will try this myself after more research, but don't want to go down a road that is fruitless if others know as much.

Thanks!

**Comment by tdalon** [comment]
Hi and thanks for your interest in my repo :-)
It is not very clear to me what you want to achieve.  Some guesses/ blind answers below:
In AHK you can easily paste the plain text content of the clipboard example see in my Clip library Clip_Paste(Clipboard)

For an example of transformation of clipboard content from Teams, you may be interested in the Teams_SmartReply feature: it will parse the HTML clipboard content to extract some parts of it. (See https://tdalon.blogspot.com/2020/11/teams-shortcuts-smart-reply.html)

If you tell me more about what you want to do, I may better help.

**Comment by nmz787-intel** [comment]
Hi Thierry, basically I want to over-ride the copy-to-clipboard functionality that Teams has (i.e. CTRL-C behavior). I *only* want the selected text to be copied, yet I often get the username and timestamp copied too, or sometimes the next or previous conversation.

I've been trying to figure out how to do this with AHK, but simple things like `ControlGet, text, Selected` aren't working. I tried your `AccViewer.ahk` hoping that would shed some light on how to approach it, but I don't get much info from the mouse hovering over the selected text in Teams. I was just looking at the SmartReply code and working on interpreting it.

**Comment by tdalon** [comment]
I think the Teams_SmartReply implementation might help you for implementing what you want.
You will need to parse the HTML code copied from the clipboard to extract what you want to paste.
Unfortunately there is (afaik) no documentation of how the Html is structured so you will have to go by trial-and-error/ reverse engineering.

Alternatively maybe this teams CLI might work for you:  [https://github.com/fossteams/teams-cli](https://github.com/fossteams/teams-cli)
The screenshot there looks like exactly what you are looking for. (I have no experience with it)

**Comment by nmz787-intel** [comment]
Hi, were you able to figure out a solution? I checked your SmartReply code, but the section where it got the data from Teams still had all the metadata.

**Comment by tdalon** [comment]
No. I left you have a look with 2 possible ways (see my previous answer). It isn't clear to me exactly what you want to achieve. Therefore I have closed the issue here.

**Comment by nmz787-intel** [comment]
Ok, I just don't want the metadata to be included in clipboard data after copying from teams message. Metadata meaning sender/receiver name, timestamp. I tried hacking on the web interface for teams, intercepting the clipboard event, but the obfuscated javascript code was too difficult to make much progress even after several hours.
