### ISSUE TITLE
Mute while screen-sharing (Window not found)

### ISSUE THREAD

**Issue by HerrRiebmann** [tdalon/ahk#13]
After adding another Button to `IsMeetingWindow(TeamsEl,Active:= true)`
`if (TeamsEl.FindFirstBy("AutomationId=meeting-apps-add-btn") or TeamsEl.FindFirstBy("AutomationId=hangup-btn") or TeamsEl.FindFirstBy("AutomationID=microphone-button"))`
my mute-shortcut works almost all the time. On calls and meetings.
But in a single cirqumstance, the window to mute cannot be found: Sharing a screen puts the main meeting-window in the background and an overlay window appears in the corner. This will not be found, even if it has a mute or hangup button. I guess due to a missing windows-title:

![grafik](https://user-images.githubusercontent.com/15670869/196140455-57e12000-c1db-4b1a-8421-e1ea771ce716.png)

What works is clicking on this tiny overlaied windows and get the original meeting window back on the screen.
I´ve tried to use "Window Spy", which didn´t helped me at all :(

My current AHK script:
```
; -------------------------------------------------------------------------------------------------------------------
Teams_GetMeetingWindow(Mode :=0, Activate:=false){
; Syntax: hwnd := Teams_GetMeetingWindow(Mode:=0)
;         UIAEl := Teams_GetMeetingWindow(Mode:=1|2,Activate:=true|false*)
;   If window is not found, hwnd is empty
; Mode=1: return Call in progress Share window 
; Mode=2 return Meeting window even if Call in progress Share Window
; See implementation explanations here: 
;   https://tdalon.blogspot.com/2022/07/ahk-get-teams-meeting-win.html

UIA := UIA_Interface()
WinGet, Win, List, ahk_exe Teams.exe
Loop %Win% {
    WinId := Win%A_Index%
    TeamsEl := UIA.ElementFromHandle(WinId)
    
    If IsMeetingWindow(TeamsEl)  {
        if (Mode = 0)
            return WinId  
        Else
            return TeamsEl     
    }
    If RegExMatch(TeamsEl.Name,"Microsoft Teams Call in progress.*") {
        If (Mode =1) {
            if Activate
                WinActivate, ahk_id %WinId%
            return TeamsEl
        }
        Else If (Mode = 2) {
            El:=  TeamsEl.FindFirstByNameAndType("Call is in progress", "text", , 1) ; partial match
            If El {
                El.Click()
                Sleep 500
                TeamsEl := Teams_FindMeetingWindow(Activate)
                return TeamsEl
            }
        }
    }

    ;MsgBox % TeamsEl.DumpAll()
} ; End Loop

TrayTip, Could not find Meeting Window! , No unminmized active Teams meeting window!.,,0x2
} ; eofun


; -------------------------------------------------------------------------------------------------------------------

Teams_FindMeetingWindow(Activate:= false) {
; Loop through Teams.exe Window to find Meeting Window
; Try multiple times untill it is found
UIA := UIA_Interface()
Loop, 3 {
    WinGet, Win, List, ahk_exe Teams.exe
    Loop %Win% {
        WinId := Win%A_Index%
        TeamsEl := UIA.ElementFromHandle(WinId)
        
        If IsMeetingWindow(TeamsEl)  {
            if Activate
                WinActivate, ahk_id %WinId%
            return TeamsEl     
        }
    }
    Sleep 500
}
TrayTip, Could not find Meeting Window! , No unminmized active Teams meeting window!.,,0x2
} ; eofun

; ---------------------------------------------------------
IsMeetingWindow(TeamsEl,Active:= true){
if (TeamsEl.FindFirstBy("AutomationId=meeting-apps-add-btn") or TeamsEl.FindFirstBy("AutomationId=hangup-btn") or TeamsEl.FindFirstBy("AutomationID=microphone-button"))
    if (Active)
        return !TeamsEl.FindFirstByName("Resume") ; Exclude On-hold meetings with Resume button
return false
} ; eofun

; MICROSOFT TEAMS - Toggle Mute
+^!M::
WinGet, PrevWinId, ID, A	; Save the current window ID
WinId := Teams_GetMeetingWindow()
if (WinId <> "")
{
	WinActivate, ahk_id %WinId%
	SendInput ^+m ; toggle mute Ctl+Shift+m
	Sleep 200
	WinActivate ahk_id %PrevWinId% ; Restore previous window focus
}
;else
;	MsgBox, 1: WinIdValue (%WinId%)
```

It would be great to enhance the script to find this little window. Or give me an advice how to find out the window-title and/or button name.
Thanks a lot in advance!

**Comment by tdalon** [comment]
Hallo and thanks for your interest in my code.
I had a mistake in the Teams_GetMeetingWindow() function for the special case where you have this Share/Call in progress window. (I had only tested with no participants)
Have a look in the repo.
I would not change the IsMeeting function as you did because else it will return this Share / Call in progress window - which I want to distinguish (see the arguments of Teams_GetMeetingWindow)

The part catching the Share/ Call in progress (CIP) window and clicking on it is at the end of the function - code extract below:
```
If RegExMatch(TeamsEl.Name,"Microsoft Teams Call in progress.*") {
        If (Mode = 1) {
            if Activate
                WinActivate, ahk_id %WinId%
            return TeamsEl
        }
        Else If (Mode = 2) {
            
            El := TeamsEl.FindFirstByType("image")
            if !El
                El:=  TeamsEl.FindFirstByNameAndType("Call is in progress", "text", , 1) ; partial match ; weird case: nobody joined the meeting
            If El {
                El.Click()
                Sleep 500
                TeamsEl := Teams_FindMeetingWindow(Activate)
                return TeamsEl
            }
        }
    }

```
- - -
Note: The mute functionality here will work without activating the real meeting window - using the buttons in the Share/ CIP window. Depending on the case it is enough to get the CIP or you may want explictly the real meeting window. This is why I have added this Mode option in the syntax:

Teams_GetMeetingWindow(Mode :=0, Activate:=false){
; Syntax: hwnd := Teams_GetMeetingWindow(Mode:=0)
;         UIAEl := Teams_GetMeetingWindow(Mode:=1|2,Activate:=true|false*)
;   If window is not found, hwnd is empty
; Mode=1: return Share/ Call in progress window 
; Mode=2 return Meeting window even if Call in progress Share Window is active

**Comment by HerrRiebmann** [comment]
Hello Thierry,
thanks a lot for your fast reply and detailed information!
I´ve modified the mentioned part of the function and rolled back my changes. But just tested it on a call and a meeting, without sharing myself. As soon as I tested that, I´ll give a feedback on that!

The explaination in the comment for Mode 1 & 2 was not clear enough for me to understand. But now I got it :)

My solution is an "Emergency stop", which emulates a keyboard via bluetooth. It just needs a powersupply and must be somewhere near the notebook. On an active connection the blue LED lights up and on mute the red one gets in place.
Key´s and some more settings can be changed on a configuration website, reachable via WiFi. Hosted on the ESP32 microcontroller, which is the "heart" of this case.
![grafik](https://user-images.githubusercontent.com/15670869/196205986-da5a51ed-acf0-4221-acfb-b669ed6a79a9.png)

![grafik](https://user-images.githubusercontent.com/15670869/196206633-77dced38-df20-4146-92c6-36f2f1779714.png)
The idea was to (un-)mute the call/meeting/whatever, while doing something different on another screen.

Best regards, and thanks for your help!

**Comment by tdalon** [comment]
You might want to use Teamsy to do some actions on Teams from your emergency stop button directly without sending a hotkey. 
This post might be interesting for you in this case https://tdalon.blogspot.com/2022/03/ahk-command-line.html

**Comment by HerrRiebmann** [comment]
Thanks, I´ve already read about that possibility. But this would require a static USB connection and an additional program/service, which connects via COM-Port and executes the cmd.
With my approach (_send keystrokes as a keyboard_), there is one stage less. Less stages, less potentially issues :)

On my today´s tests I could not mute a meeting, when the window is minimized:
![grafik](https://user-images.githubusercontent.com/15670869/196398113-2291749f-3f88-4c96-8503-ba39e19e9594.png)
Is there any logging, which I can use to determine the correct window?
Tried it with `Mode:=1` and `Mode:=2`, as well. But it also didn´t found the right window.

Maybe it´s related to my german installation? Will `Microsoft Teams Call in progress.` be translated or is this an internal state?

Sorry for bothering you. If you tell me how to find out the window-/element-names, I´ll investigate this by myself. The Taskmanager, Window Spy or Window Title does not show anything meaningful :-/

**Comment by tdalon** [comment]
Oh yes it might be due to your language.
I use the Windows Accessibility Insights Tool https://accessibilityinsights.io/docs/windows/overview/ to view the properties.

See also the UIA AHK YouTube channel by Joe/The-Automator here https://www.youtube.com/watch?v=6_4m4YeuRI4&list=PL3JprvrxlW27QIhDecJaprILS2TiDnQpM

**Comment by HerrRiebmann** [comment]
Thank you, that helped to create a log file with all that information.

`FileAppend,% TeamsEl.DumpAll(),C:\Temp\log%A_now%.txt`
Putting this one line above _End Loop_

If nothing is found, there will be three files. The main Teams window, the minimized (_but inactive_) window and the small overlay window.

**Szenario:**
The Call/Meeting was minimized or the screen is shared.
All cases will open this little topmost window in the bottom right corner. This window contains `Microsoft Teams Call in progress.*` or in my case `Microsoft Teams Anruf wird durchgeführt*`.
This would take place in Mode 1 or 2.

For Mode 0 (_preset_) the method `IsMeetingWindow()` will search for the automation ID´s. As I now found out, the Button is called `hangup-button` and not `hangup-btn` like in the regular window.
I´ve enhanced the method to the button, but *drumroll* the small window just doesn´t accept the Shift+Ctl+M shortcut :(
Controlling the inactive, minimized window also does not seem to work. I can see the focus changing to the icon in the taskbar and nothing more.

For now I don´t get further with that. I guess it´s not possible to mute, when the window is minimized (_by manually doing so or sharing the screen_). So I need to ensure the window is active and only in the background, not minimized.

Thanks for your support!

**Comment by tdalon** [comment]
Have a look at the Teams_Mute function: this shall answer your questions.
Yes you are right with the Share/CIP Window the hotkey does not work. but you can click on the button.

You might need to change the code to get the elements with your German language setting (esp. Mute and Unmute)

Advantage of the implementation here is that now you can not only toggle the mute state but really change it as you need.

I could think about supporting other languages but for now the request was too low, the effort too high and benefit for me =0. But you can reuse the code as it fits better for your language setting.

**Comment by HerrRiebmann** [comment]
Allright, got it!

There were some struggle with german umlaute like "Teams Anruf wird durchgef**ü**hrt", which breaks the whole script.

My current solution seemed to work under all circumstances, so far.
```
+^!M::
WinGet, PrevWinId, ID, A	; Save the current window ID
WinId := Teams_GetMeetingWindow()
if (WinId <> "") {
	WinActivate, ahk_id %WinId%
	SendInput ^+m ; toggle mute Ctl+Shift+m
	Sleep 200
	WinActivate ahk_id %PrevWinId% ; Restore previous window focus
}
else
	Teams_Mute()
```

Changing one line in` Teams_GetMeetingWindow()`
```
If RegExMatch(TeamsEl.Name,"Microsoft Teams Call in progress.*") {
If RegExMatch(TeamsEl.Name,"Microsoft Teams Anruf wird*") {
```
and Germanizing those parts in `Teams_Mute()`
```
El :=  TeamsEl.FindFirstByNameAndType("Mikrofon stummschalten", "button",,2)
El :=  TeamsEl.FindFirstByNameAndType("Stummschaltung aufheben", "button",,2)
```

What a journey ;) Thanks very much for your support!

**Comment by tdalon** [comment]
Happy you could adapt the code for your German language setting.
I'll close the issue.
