### ISSUE TITLE
[FR] Teamsy - Join Meeting and Focus + Fullscreen

### ISSUE THREAD

**Issue by megamorphg** [tdalon/ahk#14]
I'd like to automate a few very frequent clicks in Teams.

I find myself clicking a meeting's Join button (either on my calendar or via the tray notification) to open the pre-meeting Join menu.

After this menu pops up I usually click Join (or sometimes the Transfer button to transfer from a different device).

After joining the meeting I always do the same thing:
1. Maximize the window and move it to X screen. I can automate this with basic AHK.
2. Enable full screen and focus on content. I cannot automate this with basic AHK.

Do we have a function for step #2 or are those actions are unreachable? It would also be great to have some function to check if the active teams window is already focused (returning true or false).

**Comment by tdalon** [comment]
Hi
Have a look at the [blog posts](https://tdalon.blogspot.com) related to the code. Some articles explains what can be done and is implemented.
For example this article might be closed to what you are looking for: [Quickly Join Teams Meeting](https://tdalon.blogspot.com/2023/02/teams-quick-join-meeting.html)

You can also have a look at the list of functions available in the Teams Library in the source code [Lib/Teams.ahk](https://github.com/tdalon/ahk/blob/main/Lib/Teams.ahk)

Regarding the Focus function, I have tried to action the meeting actions functions some time ago but could not find a proper way to do it.

See my documentation at that time here https://tdalon.blogspot.com/2022/09/ahk-uia-teams-meeting-actions.html

For the Fullscreen function this was my last "solution" and is implemented: https://tdalon.blogspot.com/2022/09/ahk-teams-meeting-toggle-fullscreen.html
Note it is only a toggle. I don't know anyway to get the focus state but won't really need it also. (For the mute function I've found a way to get the state but note that the implementation is ENG language specific.)

Maybe you can find another way but my experience is that the Microsoft client is hard to tame.

So I would close here your request with this unsatisfactory answer, if you don't mind.

**Comment by megamorphg** [comment]
That is a great exploration of the subject, I think I will use UIA and mouse clicks/keyboard to do full screen, at least for joining the meeting initially. Thank you!
