### ISSUE TITLE
[Request] Teamsy - Convert Copied Image to Clipboard

### ISSUE THREAD

**Issue by megamorphg** [tdalon/ahk#15]
Currently, when doing Teams's Copy Image action, it puts text in the clipboard instead similar to:
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAi4AAAFqCAYAAAA9a9E4AAAgAElEQVR4nOydd3xUVfr...">`

Apparently, this is for security reasons:
https://learn.microsoft.com/en-us/answers/questions/857548/images-copied-from-chat-is-not-copied-to-clipboard

It hasn't received much upvotes on the portal...
https://feedbackportal.microsoft.com/feedback/idea/0c420a9b-ae9a-ed11-a81b-000d3a0450e3

Looks like they won't fix it and most people are just downloading in order to copy paste across apps.

Is it possible to add a function to Teamsy.ahk that could convert what's in the clipboard to a paste-able image?
I could then clipboard copy and then have a hotkey that calls the function... and then finally paste normally.

**Comment by tdalon** [comment]
Hi Ahmed. This is my answer https://tdalon.blogspot.com/2023/06/workaround-copypaste-images.html
I won't implement it in the Teams* Tools (since it isn't specific to Teams only) but I have implemented it in the NWS PowerTool in the [IntelliPaste](https://tdalon.github.io/ahk/IntelliPaste) feature.

**Comment by tdalon** [comment]
I will close the issue if it is ok for you.

**Comment by megamorphg** [comment]
Works perfectly! (it seems to add a return carriage in beginning but doesn't matter)
