### ISSUE TITLE
Unable to get URL from OneDrive/ SharePoint file sync location (Japanese OS)

### ISSUE THREAD

**Issue by piconex** [tdalon/ahk#17]
Hi, I appreciate your great works.

I'd like to use NWS.exe to [get URL from OneDrive/ SharePoint file sync location](https://tdalon.blogspot.com/2023/02/sharepoint-sync-get-url.html). So I tried to copy and "IntelliPaste" a file from sync location, but it did not work. I need your help to find the cause. 

More information is written below. I'm sorry for my poor English.

- IntteliCopy(Ctrl + Shift + V in browser)  worked well.

- When I tried to refresh SPSync.ini(Menu > Stting > IntelliPaste), the following error window popped out.
![ScrSht_Error_SPSync](https://github.com/tdalon/ahk/assets/97817903/99f1ea13-b036-47f1-a0dd-ef8814e0dc16)
  
  >Specifically: The specified file cannot be found.

- When I tried to check for update, the following error window popped out.
![ScrSht_Error_Update](https://github.com/tdalon/ahk/assets/97817903/71340d17-80a0-479d-be75-d041c5d02634)
  
  >Specifically: This version of "%1" is incompatible with the version of Windows you are running. Please check your computer's system information and then contact the software publisher.

- My computer's system information
  - Edition: Windows 10 Enterprise
  - Version: 21H2

- I suspect my computer's Japanese enviroment causes the problems. So I tried to compile NWS.exe myself from the source files to find out more about it, but I ran into another problem that nonexistent function "R4J_IsUrl" is called in Jira.ahk.

Thanks

**Comment by tdalon** [comment]
Hi and thanks for your interest in my code. 
I have added the missing R4J Lib. It could be some other files are missing or you get some other errors because I haven't checked-in everything. Please report the error in this case.

I would advise you to test first with the source code before compiling (you could debug with the source)
I have no experience with a Japanese OS. Could be problematic because of the special characters. 
I would be glad if you share your learnings what is not Japanese compatible in my code.

**Comment by piconex** [comment]
Thank you for replying and adding R4J. I found two more undefined functions, written below. Add them to lib please.

- `XL_Handle()` in lib/Jira.ahk
- `HttpGet()` in lib/Blogger.ahk

**Comment by tdalon** [comment]
> Thank you for replying and adding R4J. I found two more undefined functions, written below. Add them to lib please.
> 
> * `XL_Handle()` in lib/Jira.ahk
> * `HttpGet()` in lib/Blogger.ahk

I have added the two files.
Might be good for you to only extract the IntelliPaste part out of the script.

**Comment by piconex** [comment]
I'm sorry for the delay in replying. I haven't solved the problem in NWS yet, but I have found the way to get the URL w/o 3rd party tools, written below. 

1. Open the Local Group Policy Editor
1. Click "Windows Setting" > "Security Setting" > "Local Policy" > "Security Option"
1. Enable the two item, written below

    - User Account Control: Admin Approval Mode for the Built-in Administrator account
    - User Account Control: Run all administrators in Admin Approval Mode

After above setting, I can now "copy the link" from the right-click menu. So, no longer needed to solve the problem, at least for me.
