### ISSUE TITLE
Teams PowerTools e.g. Mute not working when user have both Classic and New Clients installed - but uses Classic

### ISSUE THREAD

**Issue by dooniem** [tdalon/ahk#19]
I'm sorry for commenting on a closed issue. I noticed that when the user have both versions installed and go back to the Classic version, the code fails. I made a quick patch to get it working, not a work of art, but this is the function I changed:

```
Teams_IsNew(){
    static IsNew
    If !(IsNew = "")
        return IsNew
    
	Process, Exist, Teams.exe
	If (!ErrorLevel= 0) { ;Classic Teams
		return IsNew
	}
	Else{ ;Teams v2
		IsNew:= 1
	}
    return IsNew
} ;eofun
```

It checks if a process named "Teams.exe" is running as a process on your computer, if yes that's Classic, if not that's v2.
Not much thought went into whether checking for ms-teams.exe would be a better approach, or if this is a resource heavy operation and another approach would be "lighter"...

**Comment by tdalon** [comment]
The first implementation idea was : 
if New client not installed, then Classic/IsNew=False
Else IsNew=True except the use configures  diffently in the PowerTools.ini file

Your idea to check for the running process is a good idea that can avoid the ini file configuration. Most of the time, Teams is started at PC startup. For the case it isn't and for very few feature that can be run without Teams started (like start Teams from Launcher) I leave this last option.

I have updated the [Teams_IsNew](https://github.com/tdalon/ahk/blob/main/Lib/Teams.ahk#:~:text=@fun_teams_isnew) function

**Comment by tdalon** [comment]
I think the problem is now solved.
