### ISSUE TITLE
Could not find meeting window

### ISSUE THREAD

**Issue by harphere** [tdalon/ahk#20]
`No active Teams meeting window found`

This is the error I get when I try to mute Teams from the F12 key I have mapped to.
I downloaded what I believe to be the latest TeamsShortcuts.exe from here: https://github.com/tdalon/ahk/tree/main/PowerTools

I'm running MS Teams version: 1.6.00.29964 (64-bit). It was last updated on 11/4/2023.
I also have v2 installed but using the above 'classic' version.

**Comment by tdalon** [comment]
It might be the last compiled version was not running.
I have recompiled and pushed the latest version. Please retry with the new .exe.

Which language are you using? You might need some configuration if you are not using English.

**Comment by harphere** [comment]
New version is operating as expected for me. Thanks!
