### ISSUE TITLE
Feature Request: Add ability to set focus to current meeting

### ISSUE THREAD

**Issue by mikefarwell** [tdalon/ahk#6]
Just came across this project yesterday and I have to say, I'm thoroughly impressed. Thanks for your hard work, it's already making my life easier!

After using the app for a while, I have one request: in TeamsShortcuts could you add a shortcut to switch focus to the current meeting without taking any other action? It'd be really handy when I'm working on other things during a meeting so I don't have to dig through a bunch of windows to see the window when someone starts presenting something.

Thanks!

**Comment by tdalon** [comment]
If you look at the code in Lib/Teamsy.ahk you will see there is already a keyword to activate the meeting window. I prefer the launch by keyword rather than a hotkey. I would have to look for it to see if a hotkey is already implemented. Also what is the action when you click on the system tray icon.

**Comment by tdalon** [comment]
In TeamsShortcuts.ahk the NotifyTrayClick_208 middle click on systray icon will do a Teams_Mute. You could change this to activate the meeting window.

**Comment by tdalon** [comment]
I have added a function in Lib/Teams.ahk called Teams_ActivateMeetingWindow that you can reuse.
I have also added a global hotkey option for this - see in the Settings->Global Hotkeys (it was as simple as editing in TeamsShortcuts.ahk the line HotkeyIDList = Launcher,Mute,Video,Mute App,Share,Raise Hand,Push To Talk,Clear Cache,**Activate Meeting Window** 
![image](https://user-images.githubusercontent.com/6458444/155479481-754d3152-8116-48c8-a9c8-7e0e91436bd0.png)

**Comment by tdalon** [comment]
I have pushed the update. Both source code and compiled executables.

**Comment by mikefarwell** [comment]
Thank you!
