### ISSUE TITLE
Error at line 19 in Teamsy.ahk

### ISSUE THREAD

**Issue by machmar** [tdalon/ahk#7]
![image](https://user-images.githubusercontent.com/37036318/146891082-1311e26c-6dba-49c6-97d3-26e8df3e479d.png)

I don't really understand Autohotkey, I just downloaded the ahk folder form your github and extracted it into the Lib Folder.
This is my code:
```
#Include <Teams> 

^;::
Teams_PushToTalk()
WinActivate, ahk_exe Discord.exe
Send, ^M
return ```

**Comment by tdalon** [comment]
> I just downloaded the ahk folder form your github and extracted it into the Lib Folder.

Have [a look ](https://www.autohotkey.com/docs/commands/_Include.htm) how include/Libraries work in ahk. 
You shall have the libraries in a Lib folder below your parent script so you would need some putting together of my repo to your code.

**Comment by tdalon** [comment]
It might be also because you use an older version of AutoHotkey that does not support the Switch command.
