### ISSUE TITLE
How to use your ahk suite

### ISSUE THREAD

**Issue by gtnIIS** [tdalon/ahk#9]
Hi Thierry,
you linked me to your ahk suite a while ago and I am currently trying to get it up and running. Could you provide some documentation on how to set it up and how to use it? 
I was trying to get the entire suite to run, but ahk always finds some "FunctionLibrary not found" error. I also tried to extract some parts, that I need (mute, video on/off, raise hand) but cannot get the PowerTools Suite working.  

Anyway, some words about the entire framework would be awesome! Thanks

**Comment by tdalon** [comment]
Hi. 
It is hard to understand where you got a problem. Maybe you can explain with more details what you've tried and give a precise error message.
The PowerTools can be used as is. See documentation in the webpage: https://tdalon.github.io/ahk/
(Documentation is not complete and some parts are broken)
Alternatively you can also reuse the ahk code for your own code, see for example https://github.com/tdalon/ahk/issues/8
You need to put the Lib folder below your main script in this case.
If you tell me what you are trying to do I might better be able to guide you.

Thanks for your interest!

**Comment by gtnIIS** [comment]
Sorry for the unsufficient information...
I actually was trying to accomplish the same as in #8. I fiddled around with some self-cropped script, I took from your Lib directory but got multiple errors.  

My latest approach now was to set up the script from #8 and having Lib next to the script. I also get multiple warnings, stating that some bits of code will never get called but it doesn't break. However the shortcut I set does not have any effect. I tried multiple hotkeys instead of `#^!M:: ; (un)mute MS Teams`:  

`#^!M::`  
`LControl & Y:: ; I used that one before` 
`^+m::`

I got no error message to provide. The first warning is the following:

```Warning in #include file
"...\Lib\WinClip.ahk":
    This line will never execute, due to Throw preceeding it.
      ...
      113: Throw.Exception("Error in '"funcName"':
      ...
      113: Return, 0
```

Any advice?

**Comment by tdalon** [comment]
Can you get the script from #8 running (so we start with a good basis)? 
(I don't know how to get warnings in ahk - sounds interesting)

**Comment by gtnIIS** [comment]
Sorry for getting back so late...   
So, yes I tried the script from #8 but no I couldn't get it to work. But at least the setup should be correct: script in a directory "autohotkey", the Lib directory next to it.  
I still get the warnings when executing the script (see above).  
I'd appreciate any further help

**Comment by tdalon** [comment]
No idea why you can't get the simple script running. I fear you will have to debug yourself. I would first check if the Teams function is properly called.

**Comment by gtnIIS** [comment]
Hi, I am giving it a new try. I removed everything regarding ahk from disk and reinstalled ahk and downloaded your libs again.
I still get the warnings.  
Which ahk version are you using for tests? I have the current: 1.1.33.11

**Comment by gtnIIS** [comment]
it works now... Still getting the warnings but the script does what it is supposed to do. 😄

**Comment by tdalon** [comment]
I have checked the warnings and did some cleanup.
(The WinClip library is a third-party/ not from myself.)
You can see the updates in the repo.) Keep also checking for updates because the code is quite alive and you might miss some improvements if not.
